apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lockcd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lockcd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lockcd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lockcd.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      containers:
      - name: lockcd
        image: "{{ .Values.lockcd.image.repository }}:{{ .Values.lockcd.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.lockcd.image.pullPolicy }}
        securityContext:
          privileged: true
        env:
        - name: LOCKC_CHECK_LSM_SKIP
          value: "1"
{{- if .Values.lockcd.debug.enabled }}
        - name: LOCKC_DEBUG
          value: "1"
{{- end }}
        volumeMounts:
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: bin-runc
          mountPath: /host/usr/bin/runc
        - name: sbin-runc
          mountPath: /host/usr/sbin/runc
        - name: local-bin-runc
          mountPath: /host/usr/local/bin/runc
        - name: local-sbin-runc
          mountPath: /host/usr/local/sbin/runc
        - name: run-containerd-bundle
          mountPath: /run/containerd/io.containerd.runtime.v2.task
      serviceAccountName: {{ include "lockc.serviceAccountName" . }}
      tolerations:
      - operator: Exists
      volumes:
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: bin-runc
        hostPath:
          path: /usr/bin/runc
      - name: sbin-runc
        hostPath:
          path: /usr/sbin/runc
      - name: local-bin-runc
        hostPath:
          path: /usr/local/bin/runc
      - name: local-sbin-runc
        hostPath:
          path: /usr/local/sbin/runc
      - name: run-containerd-bundle
        hostPath:
          path: /run/containerd/io.containerd.runtime.v2.task
